### ISSUE TITLE
Solc not resolving versions correctly

### ISSUE THREAD

**Issue by shunkakinoki** [evmts/evmts-monorepo#355]
I get an error on compile even if the solc version specified in tsconfig.json matches the contracts

Minimal reproducible example is here:
https://github.com/shunkakinoki/evmts-next-example/tree/bug/355

```
  "compilerOptions": {
    "plugins": [
      {
        "name": "@evmts/ts-plugin",
        "compiler": {
          "foundryProject": true,
          "solcVersion": "0.8.18"
        },
      }
    ],
  }
```

The error is below:

    message: 'Source file requires different compiler version (current compiler is 0.8.20+commit.a1b79de6.Emscripten.clang) - note that nightly builds are considered to be strictly less than the released version',

**Comment by roninjin10** [comment]
Looks like we need to add detection that makes sure the correct version of solc is installed in package.json so folks get a more actionable error message.  We could even add a prompt like "would you like us to install the correct version?"
