### ISSUE TITLE
Migrate to viem

### ISSUE THREAD

**Issue by jxom** [evmts/evmts-monorepo#47]
For speed, stability, and the ultimate developer experience 🤠

**Comment by roninjin10** [comment]
Done https://github.com/evmts/evmts-monorepo/commit/0d42c2e32d326f1c73520da5b5b075dbbd71c5af

**Comment by roninjin10** [comment]
@jxom I added some documentation about how this library will work with viem.  

Here is docs about how to initialize a viem contract: https://evmts-monorepo-docs.vercel.app/reference/contract.html

Here is docs about how to set up the transport in a viem client so it talks to the local vm: https://evmts-monorepo-docs.vercel.app/reference/http-fork.html

Here are docs about how to execute forge scripts: https://evmts-monorepo-docs.vercel.app/reference/execute.html

I have no implementation yet these are purely just specing out how I think the API should work
