### ISSUE TITLE
docs: Add developer docs

### ISSUE THREAD

**Issue by roninjin10** [evmts/evmts-monorepo#48]
# Summary

Add developer docs

## Why

We want contributions

## What

- Create developer doc one pager in the vuepress docs
- link to it in the contributing.md
- polish contributing.md

## How

- create a diagram of how the runtime works
- create a diagram of how the build works
- create docs about how to create a plugin
- keep any repo specific docs like how to set up repo in the github repo off the docs

**Comment by roninjin10** [comment]
Developer docs currently deployed here https://evmts-monorepo-docs.vercel.app/reference/execute.html

**Comment by roninjin10** [comment]
Worked on this last weekend.   The highest level docs for the core library are written.   Still need to write the plugin docs

**Comment by roninjin10** [comment]
- Polished the getting started
- Changing the API to a more ergonomic client.query and client.mutate.  Docs are not converted yet except in a few spots
- Started adding guides such as cheat-codes ethers.js usage best practices ect.

**Comment by roninjin10** [comment]
broke up smaller tickets.  After I land all of them I will close this

**Comment by yoursmanjunad** [comment]
Hey, may I work on this? Can you please assign this to me?

**Comment by roninjin10** [comment]
@yoursmanjunad sorry didn't see this comment til now! There are plenty of issues to work on including documentation. Reach out if you are interested in anything
