### ISSUE TITLE
build: Switch npm install to bun

### ISSUE THREAD

**Issue by roninjin10** [evmts/evmts-monorepo#512]
Switch to bun for faster installs. Last versions I tried 1.3 had issues

**Comment by Jarred-Sumner** [comment]
Let us know if you run into any more issues

**Comment by roninjin10** [comment]
@Jarred-Sumner I was able to migrate but my vitest coverage broke on ci only. Vitest coverage works locally though so I have coverage as the only ci task still using pnpm but everything else successfully migrated over! All the issues I was seeing in 1.3 are gone.
